before_script:
  - bundle exec rake db:migrate RAILS_ENV=test

branches:
  only:
  - master
  - develop

addons:
  code_climate:
    repo_token: a87c36225345cd75f1be6a24cc3ffdec4461d603c9f92ff98a80c19af8f81fa7

language: ruby
rvm:
  - 2.2.1

after_succes:
 - "openssl aes-256-cbc -K $encrypted_cab6a4cb5a16_key -iv $encrypted_cab6a4cb5a16_iv -in config/deploy/deploy_id_rsa.enc -out config/deploy/deploy_id_rsa -d"
 - "eval $(ssh-agent)"
 - "chmod 600 config/deploy/deploy_id_rsa"
 - "ssh-add config/deploy/deploy_id_rsa"
 - "gem install capistrano-rails"
 - "cap production deploy"
