require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AcademicInformationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # AcademicInformation. As you add validations to AcademicInformation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcademicInformationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all academic_informations as @academic_informations" do
      academic_information = AcademicInformation.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:academic_informations)).to eq([academic_information])
    end
  end

  describe "GET #show" do
    it "assigns the requested academic_information as @academic_information" do
      academic_information = AcademicInformation.create! valid_attributes
      get :show, params: {id: academic_information.to_param}, session: valid_session
      expect(assigns(:academic_information)).to eq(academic_information)
    end
  end

  describe "GET #new" do
    it "assigns a new academic_information as @academic_information" do
      user = FactoryGirl.create(:user)
      sign_in user
      get :new, user_id: user.to_param  
      expect(assigns(:academic_information)).to be_a_new(AcademicInformation)
    end
  end

  describe "GET #edit" do
    it "assigns the requested academic_information as @academic_information" do
      academic_information = AcademicInformation.create! valid_attributes
      get :edit, params: {id: academic_information.to_param}, session: valid_session
      expect(assigns(:academic_information)).to eq(academic_information)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AcademicInformation" do
        expect {
          post :create, params: {academic_information: valid_attributes}, session: valid_session
        }.to change(AcademicInformation, :count).by(1)
      end

      it "assigns a newly created academic_information as @academic_information" do
        post :create, params: {academic_information: valid_attributes}, session: valid_session
        expect(assigns(:academic_information)).to be_a(AcademicInformation)
        expect(assigns(:academic_information)).to be_persisted
      end

      it "redirects to the created academic_information" do
        post :create, params: {academic_information: valid_attributes}, session: valid_session
        expect(response).to redirect_to(AcademicInformation.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved academic_information as @academic_information" do
        post :create, params: {academic_information: invalid_attributes}, session: valid_session
        expect(assigns(:academic_information)).to be_a_new(AcademicInformation)
      end

      it "re-renders the 'new' template" do
        post :create, params: {academic_information: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested academic_information" do
        academic_information = AcademicInformation.create! valid_attributes
        put :update, params: {id: academic_information.to_param, academic_information: new_attributes}, session: valid_session
        academic_information.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested academic_information as @academic_information" do
        academic_information = AcademicInformation.create! valid_attributes
        put :update, params: {id: academic_information.to_param, academic_information: valid_attributes}, session: valid_session
        expect(assigns(:academic_information)).to eq(academic_information)
      end

      it "redirects to the academic_information" do
        academic_information = AcademicInformation.create! valid_attributes
        put :update, params: {id: academic_information.to_param, academic_information: valid_attributes}, session: valid_session
        expect(response).to redirect_to(academic_information)
      end
    end

    context "with invalid params" do
      it "assigns the academic_information as @academic_information" do
        academic_information = AcademicInformation.create! valid_attributes
        put :update, params: {id: academic_information.to_param, academic_information: invalid_attributes}, session: valid_session
        expect(assigns(:academic_information)).to eq(academic_information)
      end

      it "re-renders the 'edit' template" do
        academic_information = AcademicInformation.create! valid_attributes
        put :update, params: {id: academic_information.to_param, academic_information: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested academic_information" do
      academic_information = AcademicInformation.create! valid_attributes
      expect {
        delete :destroy, params: {id: academic_information.to_param}, session: valid_session
      }.to change(AcademicInformation, :count).by(-1)
    end

    it "redirects to the academic_informations list" do
      academic_information = AcademicInformation.create! valid_attributes
      delete :destroy, params: {id: academic_information.to_param}, session: valid_session
      expect(response).to redirect_to(academic_informations_url)
    end
  end

end
