require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PersonalInformationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PersonalInformation. As you add validations to PersonalInformation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: "My name",
    email: "foo@mail.com",
    rg: "1234567",
    cpf: "12345678901"}
#   skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    {name: "My name",
    email: "invalid_email",
    rg: "123456",
    cpf: "1234567890"}
#    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PersonalInformationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all personal_informations as @personal_informations" do
      personal_information = PersonalInformation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:personal_informations)).to eq([personal_information])
    end
  end

  describe "GET #show" do
    it "assigns the requested personal_information as @personal_information" do
      personal_information = PersonalInformation.create! valid_attributes
      get :show, {:id => personal_information.to_param}, valid_session
      expect(assigns(:personal_information)).to eq(personal_information)
    end
  end

  describe "GET #new" do
    it "assigns a new personal_information as @personal_information" do
      get :new, {}, valid_session
      expect(assigns(:personal_information)).to be_a_new(PersonalInformation)
    end
  end

  describe "GET #edit" do
    it "assigns the requested personal_information as @personal_information" do
      personal_information = PersonalInformation.create! valid_attributes
      get :edit, {:id => personal_information.to_param}, valid_session
      expect(assigns(:personal_information)).to eq(personal_information)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PersonalInformation" do
        expect {
          post :create, {:personal_information => valid_attributes}, valid_session
        }.to change(PersonalInformation, :count).by(1)
      end

      it "assigns a newly created personal_information as @personal_information" do
        post :create, {:personal_information => valid_attributes}, valid_session
        expect(assigns(:personal_information)).to be_a(PersonalInformation)
        expect(assigns(:personal_information)).to be_persisted
      end

      it "redirects to the created personal_information" do
        post :create, {:personal_information => valid_attributes}, valid_session
        expect(response).to redirect_to(PersonalInformation.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved personal_information as @personal_information" do
        post :create, {:personal_information => invalid_attributes}, valid_session
        expect(assigns(:personal_information)).to be_a_new(PersonalInformation)
      end

      it "re-renders the 'new' template" do
        post :create, {:personal_information => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: "My name",
        email: "foa@mail.com",
        rg: "1234570",
        cpf: "12345678902"}
      }

      it "updates the requested personal_information" do
        personal_information = PersonalInformation.create! valid_attributes
        put :update, {:id => personal_information.to_param, :personal_information => new_attributes}, valid_session
        personal_information.reload
        expect(assigns(:personal_information)).to eql(personal_information)
        #skip("Add assertions for updated state")
      end

      it "assigns the requested personal_information as @personal_information" do
        personal_information = PersonalInformation.create! valid_attributes
        put :update, {:id => personal_information.to_param, :personal_information => valid_attributes}, valid_session
        expect(assigns(:personal_information)).to eq(personal_information)
      end

      it "redirects to the personal_information" do
        personal_information = PersonalInformation.create! valid_attributes
        put :update, {:id => personal_information.to_param, :personal_information => valid_attributes}, valid_session
        expect(response).to redirect_to(personal_information)
      end
    end

    context "with invalid params" do
      it "assigns the personal_information as @personal_information" do
        personal_information = PersonalInformation.create! valid_attributes
        put :update, {:id => personal_information.to_param, :personal_information => invalid_attributes}, valid_session
        expect(assigns(:personal_information)).to eq(personal_information)
      end

      it "re-renders the 'edit' template" do
        personal_information = PersonalInformation.create! valid_attributes
        put :update, {:id => personal_information.to_param, :personal_information => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested personal_information" do
      personal_information = PersonalInformation.create! valid_attributes
      expect {
        delete :destroy, {:id => personal_information.to_param}, valid_session
      }.to change(PersonalInformation, :count).by(-1)
    end

    it "redirects to the personal_informations list" do
      personal_information = PersonalInformation.create! valid_attributes
      delete :destroy, {:id => personal_information.to_param}, valid_session
      expect(response).to redirect_to(personal_informations_url)
    end
  end

end
