require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProfessionalProfilesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ProfessionalProfile. As you add validations to ProfessionalProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProfessionalProfilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #show" do
    it "assigns the requested professional_profile as @professional_profile" do
      professional_profile = ProfessionalProfile.create! valid_attributes
      get :show, params: {id: professional_profile.to_param, user_id: 1}, session: valid_session
      expect(assigns(:professional_profile)).to eq(professional_profile)
    end
  end

  describe "GET #new" do
    it "create a new professional_profile" do
      user = FactoryGirl.create(:user)
      sign_in user
      expect {get :new, user_id: user.id}.to change(ProfessionalProfile, :count).by(1)
    end
    it "assigns a new professional_profile as @professional_profile" do
      user = FactoryGirl.create(:user)
      get :new, user_id: user.id
      expect(assigns(:professional_profile)).to be_a(ProfessionalProfile)
      expect(assigns(:professional_profile)).to be_persisted
    end
    it "redirect created to professional profiles" do
      user = FactoryGirl.create(:user)
      get :new, user_id: user.id
      expect(response).to redirect_to([user,ProfessionalProfile.last])
    end
  end
end
